package personal.wl.mobilepointapp.entity.pos;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "BRANCH".
*/
public class BranchDao extends AbstractDao<Branch, Long> {

    public static final String TABLENAME = "BRANCH";

    /**
     * Properties of entity Branch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Braid = new Property(1, String.class, "braid", false, "BRAID");
        public final static Property Braname = new Property(2, String.class, "braname", false, "BRANAME");
        public final static Property Brasname = new Property(3, String.class, "brasname", false, "BRASNAME");
        public final static Property Bratype = new Property(4, String.class, "bratype", false, "BRATYPE");
        public final static Property Status = new Property(5, String.class, "Status", false, "STATUS");
    }


    public BranchDao(DaoConfig config) {
        super(config);
    }
    
    public BranchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BRANCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BRAID\" TEXT," + // 1: braid
                "\"BRANAME\" TEXT," + // 2: braname
                "\"BRASNAME\" TEXT," + // 3: brasname
                "\"BRATYPE\" TEXT," + // 4: bratype
                "\"STATUS\" TEXT);"); // 5: Status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BRANCH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Branch entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String braid = entity.getBraid();
        if (braid != null) {
            stmt.bindString(2, braid);
        }
 
        String braname = entity.getBraname();
        if (braname != null) {
            stmt.bindString(3, braname);
        }
 
        String brasname = entity.getBrasname();
        if (brasname != null) {
            stmt.bindString(4, brasname);
        }
 
        String bratype = entity.getBratype();
        if (bratype != null) {
            stmt.bindString(5, bratype);
        }
 
        String Status = entity.getStatus();
        if (Status != null) {
            stmt.bindString(6, Status);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Branch entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String braid = entity.getBraid();
        if (braid != null) {
            stmt.bindString(2, braid);
        }
 
        String braname = entity.getBraname();
        if (braname != null) {
            stmt.bindString(3, braname);
        }
 
        String brasname = entity.getBrasname();
        if (brasname != null) {
            stmt.bindString(4, brasname);
        }
 
        String bratype = entity.getBratype();
        if (bratype != null) {
            stmt.bindString(5, bratype);
        }
 
        String Status = entity.getStatus();
        if (Status != null) {
            stmt.bindString(6, Status);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Branch readEntity(Cursor cursor, int offset) {
        Branch entity = new Branch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // braid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // braname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // brasname
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bratype
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // Status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Branch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBraid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBraname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBrasname(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBratype(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Branch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Branch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Branch entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
