package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productDaoConfig;
    private final DaoConfig productBarCodeDaoConfig;
    private final DaoConfig productBranchRelDaoConfig;
    private final DaoConfig productBarCodeBranchRelDaoConfig;
    private final DaoConfig productClassDaoConfig;
    private final DaoConfig saleDailyDaoConfig;
    private final DaoConfig salePayModeDaoConfig;
    private final DaoConfig branchDaoConfig;
    private final DaoConfig branchEmployeeDaoConfig;
    private final DaoConfig posMachineDaoConfig;
    private final DaoConfig mobileDeviceDaoConfig;
    private final DaoConfig pmtDmRelDaoConfig;
    private final DaoConfig frontCheckDaoConfig;

    private final ProductDao productDao;
    private final ProductBarCodeDao productBarCodeDao;
    private final ProductBranchRelDao productBranchRelDao;
    private final ProductBarCodeBranchRelDao productBarCodeBranchRelDao;
    private final ProductClassDao productClassDao;
    private final SaleDailyDao saleDailyDao;
    private final SalePayModeDao salePayModeDao;
    private final BranchDao branchDao;
    private final BranchEmployeeDao branchEmployeeDao;
    private final PosMachineDao posMachineDao;
    private final MobileDeviceDao mobileDeviceDao;
    private final PmtDmRelDao pmtDmRelDao;
    private final FrontCheckDao frontCheckDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        productBarCodeDaoConfig = daoConfigMap.get(ProductBarCodeDao.class).clone();
        productBarCodeDaoConfig.initIdentityScope(type);

        productBranchRelDaoConfig = daoConfigMap.get(ProductBranchRelDao.class).clone();
        productBranchRelDaoConfig.initIdentityScope(type);

        productBarCodeBranchRelDaoConfig = daoConfigMap.get(ProductBarCodeBranchRelDao.class).clone();
        productBarCodeBranchRelDaoConfig.initIdentityScope(type);

        productClassDaoConfig = daoConfigMap.get(ProductClassDao.class).clone();
        productClassDaoConfig.initIdentityScope(type);

        saleDailyDaoConfig = daoConfigMap.get(SaleDailyDao.class).clone();
        saleDailyDaoConfig.initIdentityScope(type);

        salePayModeDaoConfig = daoConfigMap.get(SalePayModeDao.class).clone();
        salePayModeDaoConfig.initIdentityScope(type);

        branchDaoConfig = daoConfigMap.get(BranchDao.class).clone();
        branchDaoConfig.initIdentityScope(type);

        branchEmployeeDaoConfig = daoConfigMap.get(BranchEmployeeDao.class).clone();
        branchEmployeeDaoConfig.initIdentityScope(type);

        posMachineDaoConfig = daoConfigMap.get(PosMachineDao.class).clone();
        posMachineDaoConfig.initIdentityScope(type);

        mobileDeviceDaoConfig = daoConfigMap.get(MobileDeviceDao.class).clone();
        mobileDeviceDaoConfig.initIdentityScope(type);

        pmtDmRelDaoConfig = daoConfigMap.get(PmtDmRelDao.class).clone();
        pmtDmRelDaoConfig.initIdentityScope(type);

        frontCheckDaoConfig = daoConfigMap.get(FrontCheckDao.class).clone();
        frontCheckDaoConfig.initIdentityScope(type);

        productDao = new ProductDao(productDaoConfig, this);
        productBarCodeDao = new ProductBarCodeDao(productBarCodeDaoConfig, this);
        productBranchRelDao = new ProductBranchRelDao(productBranchRelDaoConfig, this);
        productBarCodeBranchRelDao = new ProductBarCodeBranchRelDao(productBarCodeBranchRelDaoConfig, this);
        productClassDao = new ProductClassDao(productClassDaoConfig, this);
        saleDailyDao = new SaleDailyDao(saleDailyDaoConfig, this);
        salePayModeDao = new SalePayModeDao(salePayModeDaoConfig, this);
        branchDao = new BranchDao(branchDaoConfig, this);
        branchEmployeeDao = new BranchEmployeeDao(branchEmployeeDaoConfig, this);
        posMachineDao = new PosMachineDao(posMachineDaoConfig, this);
        mobileDeviceDao = new MobileDeviceDao(mobileDeviceDaoConfig, this);
        pmtDmRelDao = new PmtDmRelDao(pmtDmRelDaoConfig, this);
        frontCheckDao = new FrontCheckDao(frontCheckDaoConfig, this);

        registerDao(Product.class, productDao);
        registerDao(ProductBarCode.class, productBarCodeDao);
        registerDao(ProductBranchRel.class, productBranchRelDao);
        registerDao(ProductBarCodeBranchRel.class, productBarCodeBranchRelDao);
        registerDao(ProductClass.class, productClassDao);
        registerDao(SaleDaily.class, saleDailyDao);
        registerDao(SalePayMode.class, salePayModeDao);
        registerDao(Branch.class, branchDao);
        registerDao(BranchEmployee.class, branchEmployeeDao);
        registerDao(PosMachine.class, posMachineDao);
        registerDao(MobileDevice.class, mobileDeviceDao);
        registerDao(PmtDmRel.class, pmtDmRelDao);
        registerDao(FrontCheck.class, frontCheckDao);
    }
    
    public void clear() {
        productDaoConfig.clearIdentityScope();
        productBarCodeDaoConfig.clearIdentityScope();
        productBranchRelDaoConfig.clearIdentityScope();
        productBarCodeBranchRelDaoConfig.clearIdentityScope();
        productClassDaoConfig.clearIdentityScope();
        saleDailyDaoConfig.clearIdentityScope();
        salePayModeDaoConfig.clearIdentityScope();
        branchDaoConfig.clearIdentityScope();
        branchEmployeeDaoConfig.clearIdentityScope();
        posMachineDaoConfig.clearIdentityScope();
        mobileDeviceDaoConfig.clearIdentityScope();
        pmtDmRelDaoConfig.clearIdentityScope();
        frontCheckDaoConfig.clearIdentityScope();
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public ProductBarCodeDao getProductBarCodeDao() {
        return productBarCodeDao;
    }

    public ProductBranchRelDao getProductBranchRelDao() {
        return productBranchRelDao;
    }

    public ProductBarCodeBranchRelDao getProductBarCodeBranchRelDao() {
        return productBarCodeBranchRelDao;
    }

    public ProductClassDao getProductClassDao() {
        return productClassDao;
    }

    public SaleDailyDao getSaleDailyDao() {
        return saleDailyDao;
    }

    public SalePayModeDao getSalePayModeDao() {
        return salePayModeDao;
    }

    public BranchDao getBranchDao() {
        return branchDao;
    }

    public BranchEmployeeDao getBranchEmployeeDao() {
        return branchEmployeeDao;
    }

    public PosMachineDao getPosMachineDao() {
        return posMachineDao;
    }

    public MobileDeviceDao getMobileDeviceDao() {
        return mobileDeviceDao;
    }

    public PmtDmRelDao getPmtDmRelDao() {
        return pmtDmRelDao;
    }

    public FrontCheckDao getFrontCheckDao() {
        return frontCheckDao;
    }

}
