package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FRONT_CHECK".
 */
@Entity
public class FrontCheck {

    @Id(autoincrement = true)
    private Long id;
    private String Braid;
    private java.util.Date InputDate;
    private String PosNo;
    private String OperatorId;
    private String ProId;
    private String BarCode;
    private String ClassId;
    private Double CheckQty1;
    private Double CheckQty2;
    private String ReceiptNo;
    private String ShieldNo;
    private String CheckInnerId;
    private Long SourceId;

    @Generated
    public FrontCheck() {
    }

    public FrontCheck(Long id) {
        this.id = id;
    }

    @Generated
    public FrontCheck(Long id, String Braid, java.util.Date InputDate, String PosNo, String OperatorId, String ProId, String BarCode, String ClassId, Double CheckQty1, Double CheckQty2, String ReceiptNo, String ShieldNo, String CheckInnerId, Long SourceId) {
        this.id = id;
        this.Braid = Braid;
        this.InputDate = InputDate;
        this.PosNo = PosNo;
        this.OperatorId = OperatorId;
        this.ProId = ProId;
        this.BarCode = BarCode;
        this.ClassId = ClassId;
        this.CheckQty1 = CheckQty1;
        this.CheckQty2 = CheckQty2;
        this.ReceiptNo = ReceiptNo;
        this.ShieldNo = ShieldNo;
        this.CheckInnerId = CheckInnerId;
        this.SourceId = SourceId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBraid() {
        return Braid;
    }

    public void setBraid(String Braid) {
        this.Braid = Braid;
    }

    public java.util.Date getInputDate() {
        return InputDate;
    }

    public void setInputDate(java.util.Date InputDate) {
        this.InputDate = InputDate;
    }

    public String getPosNo() {
        return PosNo;
    }

    public void setPosNo(String PosNo) {
        this.PosNo = PosNo;
    }

    public String getOperatorId() {
        return OperatorId;
    }

    public void setOperatorId(String OperatorId) {
        this.OperatorId = OperatorId;
    }

    public String getProId() {
        return ProId;
    }

    public void setProId(String ProId) {
        this.ProId = ProId;
    }

    public String getBarCode() {
        return BarCode;
    }

    public void setBarCode(String BarCode) {
        this.BarCode = BarCode;
    }

    public String getClassId() {
        return ClassId;
    }

    public void setClassId(String ClassId) {
        this.ClassId = ClassId;
    }

    public Double getCheckQty1() {
        return CheckQty1;
    }

    public void setCheckQty1(Double CheckQty1) {
        this.CheckQty1 = CheckQty1;
    }

    public Double getCheckQty2() {
        return CheckQty2;
    }

    public void setCheckQty2(Double CheckQty2) {
        this.CheckQty2 = CheckQty2;
    }

    public String getReceiptNo() {
        return ReceiptNo;
    }

    public void setReceiptNo(String ReceiptNo) {
        this.ReceiptNo = ReceiptNo;
    }

    public String getShieldNo() {
        return ShieldNo;
    }

    public void setShieldNo(String ShieldNo) {
        this.ShieldNo = ShieldNo;
    }

    public String getCheckInnerId() {
        return CheckInnerId;
    }

    public void setCheckInnerId(String CheckInnerId) {
        this.CheckInnerId = CheckInnerId;
    }

    public Long getSourceId() {
        return SourceId;
    }

    public void setSourceId(Long SourceId) {
        this.SourceId = SourceId;
    }

}
