package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MOBILE_DEVICE".
 */
@Entity
public class MobileDevice {

    @Id(autoincrement = true)
    private Long id;
    private String deviceid;
    private String posno;
    private String Status;
    private Long SourceId;

    @Generated
    public MobileDevice() {
    }

    public MobileDevice(Long id) {
        this.id = id;
    }

    @Generated
    public MobileDevice(Long id, String deviceid, String posno, String Status, Long SourceId) {
        this.id = id;
        this.deviceid = deviceid;
        this.posno = posno;
        this.Status = Status;
        this.SourceId = SourceId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceid() {
        return deviceid;
    }

    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    public String getPosno() {
        return posno;
    }

    public void setPosno(String posno) {
        this.posno = posno;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public Long getSourceId() {
        return SourceId;
    }

    public void setSourceId(Long SourceId) {
        this.SourceId = SourceId;
    }

}
