package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PayMent".
 */
@Entity
public class PayMent {

    @Id(autoincrement = true)
    private Long id;
    private String PayMentName;
    private String PayModeId;
    private String CadType;
    private Long TableId;

    public String getPayMentName() {
        return PayMentName;
    }

    public void setPayMentName(String payMentName) {
        PayMentName = payMentName;
    }

    public String getPayModeId() {
        return PayModeId;
    }

    public void setPayModeId(String payModeId) {
        PayModeId = payModeId;
    }

    public String getCadType() {
        return CadType;
    }

    public void setCadType(String cadType) {
        CadType = cadType;
    }

    public Long getTableId() {
        return TableId;
    }

    public void setTableId(Long tableId) {
        TableId = tableId;
    }

    public PayMent(String payMentName, String payModeId, String cadType, Long tableId) {
        PayMentName = payMentName;
        PayModeId = payModeId;
        CadType = cadType;
        TableId = tableId;
    }
}
