package personal.wl.mobilepointapp.entity.pos;

import android.databinding.BaseObservable;
import android.databinding.Bindable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import personal.wl.mobilepointapp.BR;


import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PayMent".
 */
@Entity
public class PayMent extends BaseObservable implements Serializable {

    @Id(autoincrement = true)
//    private Long id;
    private String PayMentName;
    private String PayModeId;
    private String CadType;

//    @Bindable
    public Double getPayMoney() {
        return PayMoney;
    }

    public void setPayMoney(Double payMoney) {
        PayMoney = payMoney;
//        notifyPropertyChanged(BR.payMoney);
    }

    private Double PayMoney;
    private Long PayMentId;

    public PayMent() {
    }

    public Long getPayMentId() {
        return PayMentId;
    }

    public void setPayMentId(Long payMentId) {
        PayMentId = payMentId;
    }


    public String getPayMentName() {
        return PayMentName;
    }

    public void setPayMentName(String payMentName) {
        PayMentName = payMentName;
    }

    public String getPayModeId() {
        return PayModeId;
    }

    public void setPayModeId(String payModeId) {
        PayModeId = payModeId;
    }

    public String getCadType() {
        return CadType;
    }

    public void setCadType(String cadType) {
        CadType = cadType;
    }


}
