package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "POS_MACHINE".
 */
@Entity
public class PosMachine {

    @Id(autoincrement = true)
    private Long id;
    private String braid;
    private String posno;
    private String Status;

    @Generated
    public PosMachine() {
    }

    public PosMachine(Long id) {
        this.id = id;
    }

    @Generated
    public PosMachine(Long id, String braid, String posno, String Status) {
        this.id = id;
        this.braid = braid;
        this.posno = posno;
        this.Status = Status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBraid() {
        return braid;
    }

    public void setBraid(String braid) {
        this.braid = braid;
    }

    public String getPosno() {
        return posno;
    }

    public void setPosno(String posno) {
        this.posno = posno;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

}
