package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRODUCT_BAR_CODE_BRANCH_REL".
 */
@Entity
public class ProductBarCodeBranchRel {

    @Id(autoincrement = true)
    private Long id;
    private String Braid;
    private String Proid;
    private String Barcode;
    private String BarMode;
    private Double Quantity;
    private Double NormalPrice;
    private Double MemberPrice;
    private String Status;
    private String Operatorid;
    private String Spec;
    private String MainFlag;
    private Long TimeStamp;
    private java.util.Date CreateDate;
    private java.util.Date UpdateDate;

    @Generated
    public ProductBarCodeBranchRel() {
    }

    public ProductBarCodeBranchRel(Long id) {
        this.id = id;
    }

    @Generated
    public ProductBarCodeBranchRel(Long id, String Braid, String Proid, String Barcode, String BarMode, Double Quantity, Double NormalPrice, Double MemberPrice, String Status, String Operatorid, String Spec, String MainFlag, Long TimeStamp, java.util.Date CreateDate, java.util.Date UpdateDate) {
        this.id = id;
        this.Braid = Braid;
        this.Proid = Proid;
        this.Barcode = Barcode;
        this.BarMode = BarMode;
        this.Quantity = Quantity;
        this.NormalPrice = NormalPrice;
        this.MemberPrice = MemberPrice;
        this.Status = Status;
        this.Operatorid = Operatorid;
        this.Spec = Spec;
        this.MainFlag = MainFlag;
        this.TimeStamp = TimeStamp;
        this.CreateDate = CreateDate;
        this.UpdateDate = UpdateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBraid() {
        return Braid;
    }

    public void setBraid(String Braid) {
        this.Braid = Braid;
    }

    public String getProid() {
        return Proid;
    }

    public void setProid(String Proid) {
        this.Proid = Proid;
    }

    public String getBarcode() {
        return Barcode;
    }

    public void setBarcode(String Barcode) {
        this.Barcode = Barcode;
    }

    public String getBarMode() {
        return BarMode;
    }

    public void setBarMode(String BarMode) {
        this.BarMode = BarMode;
    }

    public Double getQuantity() {
        return Quantity;
    }

    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    public Double getNormalPrice() {
        return NormalPrice;
    }

    public void setNormalPrice(Double NormalPrice) {
        this.NormalPrice = NormalPrice;
    }

    public Double getMemberPrice() {
        return MemberPrice;
    }

    public void setMemberPrice(Double MemberPrice) {
        this.MemberPrice = MemberPrice;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getOperatorid() {
        return Operatorid;
    }

    public void setOperatorid(String Operatorid) {
        this.Operatorid = Operatorid;
    }

    public String getSpec() {
        return Spec;
    }

    public void setSpec(String Spec) {
        this.Spec = Spec;
    }

    public String getMainFlag() {
        return MainFlag;
    }

    public void setMainFlag(String MainFlag) {
        this.MainFlag = MainFlag;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public java.util.Date getCreateDate() {
        return CreateDate;
    }

    public void setCreateDate(java.util.Date CreateDate) {
        this.CreateDate = CreateDate;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
