package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRODUCT_CLASS".
 */
@Entity
public class ProductClass {

    @Id(autoincrement = true)
    private Long id;
    private String ClassId;
    private String ClassName;
    private Long TimeStamp;
    private Double Status;
    private java.util.Date CreateDate;
    private java.util.Date UpdateDate;

    @Generated
    public ProductClass() {
    }

    public ProductClass(Long id) {
        this.id = id;
    }

    @Generated
    public ProductClass(Long id, String ClassId, String ClassName, Long TimeStamp, Double Status, java.util.Date CreateDate, java.util.Date UpdateDate) {
        this.id = id;
        this.ClassId = ClassId;
        this.ClassName = ClassName;
        this.TimeStamp = TimeStamp;
        this.Status = Status;
        this.CreateDate = CreateDate;
        this.UpdateDate = UpdateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClassId() {
        return ClassId;
    }

    public void setClassId(String ClassId) {
        this.ClassId = ClassId;
    }

    public String getClassName() {
        return ClassName;
    }

    public void setClassName(String ClassName) {
        this.ClassName = ClassName;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Double getStatus() {
        return Status;
    }

    public void setStatus(Double Status) {
        this.Status = Status;
    }

    public java.util.Date getCreateDate() {
        return CreateDate;
    }

    public void setCreateDate(java.util.Date CreateDate) {
        this.CreateDate = CreateDate;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
