package personal.wl.mobilepointapp.entity.pos;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SALE_DAILY".
 */
@Entity
public class SaleDaily implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String Braid;
    private java.util.Date SaleDate;
    private String ProId;

    public String getProName() {
        return ProName;
    }

    public void setProName(String proName) {
        ProName = proName;
    }

    private String ProName;
    private String BarCode;
    private String ClassId;
    private String IsDM;
    private String IsPmt;
    private String IsTimePrompt;
    private Double SaleTax;
    private String PosNo;
    private String SalerId;
    private String SaleMan;
    private String SaleType;
    private Double SaleQty;
    private Double SaleAmt;
    private Double SaleDisAmt;
    private Double TransDisAmt;
    private Double NormalPrice;
    private Double CurPrice;
    private Double AvgCostPrice;
    private String SaleId;
    private String InVoiceId;
    private Double Point1;
    private Double Point2;
    private Double ReturnRat;
    private Double Cash1;
    private Double Cash2;
    private Double Cash3;
    private Double Cash4;
    private Double Cash5;
    private Double Cash6;
    private Double Cash7;
    private Double Cash8;
    private Long SourceId;
    private Boolean IsReturn;
    private String OrderInnerId;

    private SaleDaily saleDaily;

    @Generated
    public SaleDaily() {
        saleDaily = this;
    }


    public SaleDaily getSaleDailyFromProduct(Product product) {
        saleDaily.setProId(product.getProid());
        saleDaily.setBarCode(product.getBarcode());
        saleDaily.setProName(product.getProName());
        saleDaily.setNormalPrice(product.getNormalPrice());
        saleDaily.setSaleQty(product.getSaleQty());
        saleDaily.setSaleAmt(product.getSaleQty() * product.getNormalPrice());
        return saleDaily;
    }

    public SaleDaily(Long id) {
        this.id = id;
    }

    @Generated
    public SaleDaily(Long id, String Braid, java.util.Date SaleDate, String ProId, String BarCode, String ClassId, String IsDM, String IsPmt, String IsTimePrompt, Double SaleTax, String PosNo, String SalerId, String SaleMan, String SaleType, Double SaleQty, Double SaleAmt, Double SaleDisAmt, Double TransDisAmt, Double NormalPrice, Double CurPrice, Double AvgCostPrice, String SaleId, String InVoiceId, Double Point1, Double Point2, Double ReturnRat, Double Cash1, Double Cash2, Double Cash3, Double Cash4, Double Cash5, Double Cash6, Double Cash7, Double Cash8, Long SourceId, Boolean IsReturn, String OrderInnerId) {
        this.id = id;
        this.Braid = Braid;
        this.SaleDate = SaleDate;
        this.ProId = ProId;
        this.BarCode = BarCode;
        this.ClassId = ClassId;
        this.IsDM = IsDM;
        this.IsPmt = IsPmt;
        this.IsTimePrompt = IsTimePrompt;
        this.SaleTax = SaleTax;
        this.PosNo = PosNo;
        this.SalerId = SalerId;
        this.SaleMan = SaleMan;
        this.SaleType = SaleType;
        this.SaleQty = SaleQty;
        this.SaleAmt = SaleAmt;
        this.SaleDisAmt = SaleDisAmt;
        this.TransDisAmt = TransDisAmt;
        this.NormalPrice = NormalPrice;
        this.CurPrice = CurPrice;
        this.AvgCostPrice = AvgCostPrice;
        this.SaleId = SaleId;
        this.InVoiceId = InVoiceId;
        this.Point1 = Point1;
        this.Point2 = Point2;
        this.ReturnRat = ReturnRat;
        this.Cash1 = Cash1;
        this.Cash2 = Cash2;
        this.Cash3 = Cash3;
        this.Cash4 = Cash4;
        this.Cash5 = Cash5;
        this.Cash6 = Cash6;
        this.Cash7 = Cash7;
        this.Cash8 = Cash8;
        this.SourceId = SourceId;
        this.IsReturn = IsReturn;
        this.OrderInnerId = OrderInnerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBraid() {
        return Braid;
    }

    public void setBraid(String Braid) {
        this.Braid = Braid;
    }

    public java.util.Date getSaleDate() {
        return SaleDate;
    }

    public void setSaleDate(java.util.Date SaleDate) {
        this.SaleDate = SaleDate;
    }

    public String getProId() {
        return ProId;
    }

    public void setProId(String ProId) {
        this.ProId = ProId;
    }

    public String getBarCode() {
        return BarCode;
    }

    public void setBarCode(String BarCode) {
        this.BarCode = BarCode;
    }

    public String getClassId() {
        return ClassId;
    }

    public void setClassId(String ClassId) {
        this.ClassId = ClassId;
    }

    public String getIsDM() {
        return IsDM;
    }

    public void setIsDM(String IsDM) {
        this.IsDM = IsDM;
    }

    public String getIsPmt() {
        return IsPmt;
    }

    public void setIsPmt(String IsPmt) {
        this.IsPmt = IsPmt;
    }

    public String getIsTimePrompt() {
        return IsTimePrompt;
    }

    public void setIsTimePrompt(String IsTimePrompt) {
        this.IsTimePrompt = IsTimePrompt;
    }

    public Double getSaleTax() {
        return SaleTax;
    }

    public void setSaleTax(Double SaleTax) {
        this.SaleTax = SaleTax;
    }

    public String getPosNo() {
        return PosNo;
    }

    public void setPosNo(String PosNo) {
        this.PosNo = PosNo;
    }

    public String getSalerId() {
        return SalerId;
    }

    public void setSalerId(String SalerId) {
        this.SalerId = SalerId;
    }

    public String getSaleMan() {
        return SaleMan;
    }

    public void setSaleMan(String SaleMan) {
        this.SaleMan = SaleMan;
    }

    public String getSaleType() {
        return SaleType;
    }

    public void setSaleType(String SaleType) {
        this.SaleType = SaleType;
    }

    public Double getSaleQty() {
        return SaleQty;
    }

    public void setSaleQty(Double SaleQty) {
        this.SaleQty = SaleQty;
    }

    public Double getSaleAmt() {
        return SaleAmt;
    }

    public void setSaleAmt(Double SaleAmt) {
        this.SaleAmt = SaleAmt;
    }

    public Double getSaleDisAmt() {
        return SaleDisAmt;
    }

    public void setSaleDisAmt(Double SaleDisAmt) {
        this.SaleDisAmt = SaleDisAmt;
    }

    public Double getTransDisAmt() {
        return TransDisAmt;
    }

    public void setTransDisAmt(Double TransDisAmt) {
        this.TransDisAmt = TransDisAmt;
    }

    public Double getNormalPrice() {
        return NormalPrice;
    }

    public void setNormalPrice(Double NormalPrice) {
        this.NormalPrice = NormalPrice;
    }

    public Double getCurPrice() {
        return CurPrice;
    }

    public void setCurPrice(Double CurPrice) {
        this.CurPrice = CurPrice;
    }

    public Double getAvgCostPrice() {
        return AvgCostPrice;
    }

    public void setAvgCostPrice(Double AvgCostPrice) {
        this.AvgCostPrice = AvgCostPrice;
    }

    public String getSaleId() {
        return SaleId;
    }

    public void setSaleId(String SaleId) {
        this.SaleId = SaleId;
    }

    public String getInVoiceId() {
        return InVoiceId;
    }

    public void setInVoiceId(String InVoiceId) {
        this.InVoiceId = InVoiceId;
    }

    public Double getPoint1() {
        return Point1;
    }

    public void setPoint1(Double Point1) {
        this.Point1 = Point1;
    }

    public Double getPoint2() {
        return Point2;
    }

    public void setPoint2(Double Point2) {
        this.Point2 = Point2;
    }

    public Double getReturnRat() {
        return ReturnRat;
    }

    public void setReturnRat(Double ReturnRat) {
        this.ReturnRat = ReturnRat;
    }

    public Double getCash1() {
        return Cash1;
    }

    public void setCash1(Double Cash1) {
        this.Cash1 = Cash1;
    }

    public Double getCash2() {
        return Cash2;
    }

    public void setCash2(Double Cash2) {
        this.Cash2 = Cash2;
    }

    public Double getCash3() {
        return Cash3;
    }

    public void setCash3(Double Cash3) {
        this.Cash3 = Cash3;
    }

    public Double getCash4() {
        return Cash4;
    }

    public void setCash4(Double Cash4) {
        this.Cash4 = Cash4;
    }

    public Double getCash5() {
        return Cash5;
    }

    public void setCash5(Double Cash5) {
        this.Cash5 = Cash5;
    }

    public Double getCash6() {
        return Cash6;
    }

    public void setCash6(Double Cash6) {
        this.Cash6 = Cash6;
    }

    public Double getCash7() {
        return Cash7;
    }

    public void setCash7(Double Cash7) {
        this.Cash7 = Cash7;
    }

    public Double getCash8() {
        return Cash8;
    }

    public void setCash8(Double Cash8) {
        this.Cash8 = Cash8;
    }

    public Long getSourceId() {
        return SourceId;
    }

    public void setSourceId(Long SourceId) {
        this.SourceId = SourceId;
    }

    public Boolean getIsReturn() {
        return IsReturn;
    }

    public void setIsReturn(Boolean IsReturn) {
        this.IsReturn = IsReturn;
    }

    public String getOrderInnerId() {
        return OrderInnerId;
    }

    public void setOrderInnerId(String OrderInnerId) {
        this.OrderInnerId = OrderInnerId;
    }

}
